// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearLogs(): $CancellablePromise<string> {
    return $Call.ByID(3546784714);
}

export function Enroll(serverURL: string, joinToken: string, deviceID: string, name: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(4021541344, serverURL, joinToken, deviceID, name, description);
}

export function GetLogs(): $CancellablePromise<$models.LogMessage[]> {
    return $Call.ByID(2435861467).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMetrics(): $CancellablePromise<$models.FormattedMetrics> {
    return $Call.ByID(2089579933).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStatus(): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(3157647386).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ResetState(): $CancellablePromise<string> {
    return $Call.ByID(39892508);
}

export function RestartAgent(): $CancellablePromise<string> {
    return $Call.ByID(3487647484);
}

export function StartAgent(): $CancellablePromise<string> {
    return $Call.ByID(3027766529);
}

export function StopAgent(): $CancellablePromise<string> {
    return $Call.ByID(1865011677);
}

// Private type creation functions
const $$createType0 = $models.LogMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FormattedMetrics.createFrom;
const $$createType3 = $models.AgentStatus.createFrom;
