// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AgentStatus {
    "isRunning": boolean;
    "isConnected": boolean;
    "isEnrolled": boolean;
    "serverUrl": string;
    "deviceId": string;
    "name": string;
    "description": string;
    "version": string;
    "statePath": string;
    "hostname": string;
    "localIp": string;
    "publicIp": string;
    "platform": string;
    "architecture": string;
    "metricsIntervalSeconds": number;
    "lastHeartbeat": string;
    "lastMetricsSent": string;
    "errorMsg": string;

    /** Creates a new AgentStatus instance. */
    constructor($$source: Partial<AgentStatus> = {}) {
        if (!("isRunning" in $$source)) {
            this["isRunning"] = false;
        }
        if (!("isConnected" in $$source)) {
            this["isConnected"] = false;
        }
        if (!("isEnrolled" in $$source)) {
            this["isEnrolled"] = false;
        }
        if (!("serverUrl" in $$source)) {
            this["serverUrl"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("statePath" in $$source)) {
            this["statePath"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("localIp" in $$source)) {
            this["localIp"] = "";
        }
        if (!("publicIp" in $$source)) {
            this["publicIp"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("architecture" in $$source)) {
            this["architecture"] = "";
        }
        if (!("metricsIntervalSeconds" in $$source)) {
            this["metricsIntervalSeconds"] = 0;
        }
        if (!("lastHeartbeat" in $$source)) {
            this["lastHeartbeat"] = "";
        }
        if (!("lastMetricsSent" in $$source)) {
            this["lastMetricsSent"] = "";
        }
        if (!("errorMsg" in $$source)) {
            this["errorMsg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentStatus($$parsedSource as Partial<AgentStatus>);
    }
}

export class FormattedMetrics {
    "timestamp": number;
    "cpuUsage": number;
    "cpuCores": number;
    "memTotalMb": number;
    "memUsedMb": number;
    "memUsage": number;
    "diskTotalGb": number;
    "diskUsedGb": number;
    "diskUsage": number;
    "storagePath": string;

    /** Creates a new FormattedMetrics instance. */
    constructor($$source: Partial<FormattedMetrics> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("cpuUsage" in $$source)) {
            this["cpuUsage"] = 0;
        }
        if (!("cpuCores" in $$source)) {
            this["cpuCores"] = 0;
        }
        if (!("memTotalMb" in $$source)) {
            this["memTotalMb"] = 0;
        }
        if (!("memUsedMb" in $$source)) {
            this["memUsedMb"] = 0;
        }
        if (!("memUsage" in $$source)) {
            this["memUsage"] = 0;
        }
        if (!("diskTotalGb" in $$source)) {
            this["diskTotalGb"] = 0;
        }
        if (!("diskUsedGb" in $$source)) {
            this["diskUsedGb"] = 0;
        }
        if (!("diskUsage" in $$source)) {
            this["diskUsage"] = 0;
        }
        if (!("storagePath" in $$source)) {
            this["storagePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormattedMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): FormattedMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormattedMetrics($$parsedSource as Partial<FormattedMetrics>);
    }
}

export class LogMessage {
    "id": number;
    "timestamp": string;

    /**
     * "info", "success", "warning", "error"
     */
    "level": string;
    "message": string;

    /** Creates a new LogMessage instance. */
    constructor($$source: Partial<LogMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): LogMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogMessage($$parsedSource as Partial<LogMessage>);
    }
}
